### ISSUE TITLE
Title string input for plot title 

### ISSUE THREAD

**Issue by brianmapes** [brianmapes/MSEplot#2]

**Comment by suvarchal** [comment]
I couldn't catch the  returned plt handle (therefore axes handle) to change the title , so I wonder if title needs to be passed as an argument like the function EnergyMassPlot in this [module](https://github.com/brianmapes/MSEplot/blob/master/mapes_utils.py)

**Comment by brianmapes** [comment]
Is that best practice, passing back the plt handle? 

Or shall we just design (and expand as needed) the argument list to a few one-line commands that are nice and clean at the calling top level? 

Which kind of call to MSEplot would you rather have in a notebook with a movable probe to explore the .zidv files you just teleported?

**Comment by suvarchal** [comment]
For functions wrapping matplotlib plots, I think the best way is to have extra arguments *args and **kwargs, that will be passed to matplotlib plotting routines inside the function. This will give control to the function user; thereon any matplotlib settings can be passed not just the title.  

 any function call should be fine for a probe, passing title in the call would make it look a bit less tedious too.

**Comment by suvarchal** [comment]
added provision for title (and other matplotlib key word arguments) to the msed_plots function.
msed_plots(pressure......,title="xyz") should work now. I will restructure code for better code stucture next days.

**Comment by brianmapes** [comment]
Success! closing issue
