### ISSUE TITLE
Can the pip publish instructions (all but the password) be put in a checklist.md in MSEplots-pkg_MetpyDependent?

### ISSUE THREAD

**Issue by brianmapes** [brianmapes/MSEplot#4]
So any time any of us makes a key edit, we can republish the package in a few steps?

**Comment by suvarchal** [comment]
yes, possible with continuous integration, where password is also hidden.

**Comment by brianmapes** [comment]
I made a dev branch for myself. I thought I could work on the plots.py heart of the package in Jupyter (using the commented-out failing import command in the 5th code line here https://github.com/brianmapes/MSEplot/blob/master/MSEplots-pkg_MetpyDependent/MSEpkg_demo.ipynb). 

Then after I work on the plotting codes until I like it better, I could issue a PR, and off it would go into master, and easily enough into pip. 

But I don't know how to work within a branch in jupyter; and also the import command in the notebook fails, as I mentioned. I am still not competent in collaborative software.

**Comment by brianmapes** [comment]
(Testing email reply)

CI might be overkill. I could just learn the password and follow a checklist.


Brian Mapes
This message was typed on a cell phone, please forgive its terseness and any errors.

On Nov 10, 2018, at 6:34 PM, Suvarchal Kumar Cheedela <notifications@github.com<mailto:notifications@github.com>> wrote:

yes, possible with continuous integration, where password is also hidden.

**Comment by brianmapes** [comment]
Testing reply-all


Brian Mapes
This message was typed on a cell phone, please forgive its terseness and any errors.

On Nov 10, 2018, at 6:34 PM, Suvarchal Kumar Cheedela <notifications@github.com<mailto:notifications@github.com>> wrote:

yes, possible with continuous integration, where password is also hidden.

**Comment by brianmapes** [comment]
I guess "branch" is too formal for just 3 of us who all have write permission. Never mind. I'll just make a side copy and pull it into github every time I sit down to a work session on it.

**Comment by brianmapes** [comment]
Oh but Wei-Ming, please make the checklist and tell me the password.

**Comment by suvarchal** [comment]
every tagged release can be automatized to be uploaded to pip, that would make more sense to make your/our life easier @brianmapes. more on email.

**Comment by brianmapes** [comment]
PyPI pubish procedure is now in README.md at https://github.com/brianmapes/MSEplot. Closing issue.
