### ISSUE TITLE
station location errors in MSEplot_USAsondes_hvClickMap.ipynb

### ISSUE THREAD

**Issue by brianmapes** [brianmapes/MSEplot#5]
I click the Miami dot and get PIT (Pittsburgh?), and other dots also fail to match station names. So close to a cool tool! Let's make it work!

**Comment by suvarchal** [comment]
The click is sensitive ( bokeh part of it) so the  closest location to the
click is set to finding closest longitude in the data ( simplest
implementation) , it should find closest lattitude and longitude. I need to
fix that with a better logic in the function.

**Comment by suvarchal** [comment]
fixed by selecting nearest station with least  L1 distance from click location
here is the gif screenshot
http://weather.rsmas.miami.edu/repository/metadata/view/MSE_plotUSclickmap.gif?element=1&entryid=051ab7d7-9cc0-4de1-9dcb-e62028f1bfd8&metadata.id=ab2c6f5a-5f9a-4fff-8310-e3e004e8f7d2
